server:
  port: 8080

spring:
  application:
    name: hostel-mess-management
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://db.njpqrplfmyclgqwzkpsu.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Hostel-mess2026
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: hmsSecretKey2024ForHostelMessManagementSystem
  expiration: 86400000 # 24 hours

# Application Configuration
app:
  meal:
    cost: 60.0
    fine-per-day: 30.0
    payment-grace-days: 7
  upi:
    id: rintocherian2006@oksbi

logging:
  level:
    com.hms: DEBUG
    org.springframework.security: DEBUG